### ISSUE TITLE
Repetición de Personalizable, en Diccionario de Datos y Glosario de términos

### ISSUE THREAD

**Issue by carlotamgm** [UNIZAR-30226-2024-08/documentacion#11]
El término Personalizable se explica tanto en Diccionario de Datos como en Glosario de términos.

Se podría solucionar dejando la definición de Personalizable únicamente en el Diccionario de datos, al aparecer en la lista de Requisitos.

**Comment by Lizerat** [comment]
Se repite porque en el glosario lo utilizamos para explicar que son y en el diccionario de datos para explicar que información tenemos que guardar en la base de datos sobre ellos. Creo que no está mal tenerlo dos veces.
