### ISSUE TITLE
Maquetar y Casos de Uso

### ISSUE THREAD

**Issue by Lizerat** [UNIZAR-30226-2024-08/documentacion#17]
Maquetar el DER y añadir Casos de Uso basados en los requisitos.

**Comment by LuciaMoralesRosa** [comment]
@jeregon1 Se ha terminado de maquetar el DER y está listo para que lo apruebes. Faltan las descripciones de casos de uso, diagrama de clases y paquetes pero será para la versión 0.2 del documento, así tenemos ya los requisitos listos.
