### ISSUE TITLE
Falta tilde en algunas palabras Póker

### ISSUE THREAD

**Issue by jeregon1** [UNIZAR-30226-2024-08/documentacion#19]
**Descripción del error**
Hay veces que Póker lleva tilde y otras que no, así que mejor estandarizar el término en el documento.

**Resultado Esperado**
Dado que creo que aparece más veces Póker con tilde actualmente, será más rápido poner tilde a todos.

**Contexto Adicional**
Claramente no es un error porque en inglés es válido, pero así mejor.

**Comment by LuciaMoralesRosa** [comment]
Corregido
