### ISSUE TITLE
Deberíamos guardar en el historial de partidas el momento de inicio de la partida

### ISSUE THREAD

**Issue by jeregon1** [UNIZAR-30226-2024-08/documentacion#20]
**Concepto que falta en la Documentación.**
Creo que sería necesario incluir en el historial de partidas cuándo se inició cada partida, ya que creo que es útil verlo para un usuario.

**Sugerir Solución**
Incluirlo en el diccionario de datos, Historial de partidas.

**Comment by LuciaMoralesRosa** [comment]
Corregido
