### ISSUE TITLE
Mínimo número de jugadores en sala pública de Póker erróneo

### ISSUE THREAD

**Issue by jeregon1** [UNIZAR-30226-2024-08/documentacion#21]
**Descripción del error**
Pone que como mínimo habrá 1 jugador en el apartado 5.1.3 del DER, RFJ-1, c)

**Resultado Esperado**
Deberían ser 2 ya que no puede jugarse al póker uno solo.

**Contexto Adicional**
En las correspondientes salas privadas sí que pone 2.

**Comment by LuciaMoralesRosa** [comment]
Como es pública te empareja con otro jugador, asi que puedes crear una sala publica de un unico jugador y la aplicacion te meterá en otra sala con al menos otro jugador.
