### ISSUE TITLE
Errata en los títulos de la Documentación y Formalización de requisitos

### ISSUE THREAD

**Issue by jeregon1** [UNIZAR-30226-2024-08/documentacion#22]
**Descripción del error**
En algunos títulos como "Requisitos no Funcionales" y "Requisitos Funcionales de los Usuarios no Autenticados", la palabra "no" tiene la n minúscula, siendo que en las siglas de dichos apartados después se incluye la N, como RNF o RFUNA.

**Resultado Esperado**
"no" debería tener la N mayúscula ya que las siglas la contienen.

**Comment by LuciaMoralesRosa** [comment]
Corregido
