### ISSUE TITLE
Observador

### ISSUE THREAD

**Issue by aroaaredondo** [UNIZAR-30226-2024-08/documentacion#5]
**Descripción del error**
En el apartado 2, se añade un observador que no se describió en la propuesta técnica.
**Resultado Esperado**
Eliminar dicha descripción de los grupos de interés y en los apartados siguientes.

**Contexto Adicional**
Cualquier otra información pertinente.

**Comment by titoMar008** [comment]
Se han borrado todos lo requisitos que tienen que ver con los observadores
