### ISSUE TITLE
Descripción de los grupos de interés

### ISSUE THREAD

**Issue by aroaaredondo** [UNIZAR-30226-2024-08/documentacion#6]
**Descripción del error**
Porque diferenciamos entre jugador y jugador de Blackjack y no aparece jugador de poker.

**Resultado Esperado**
Añadir una descripción de jugador de poker o no hacer diferencia entre jugador normal y jugado de blackJack

**Contexto Adicional**
Cualquier otra información pertinente.

**Comment by titoMar008** [comment]
Ya se ha añadido el jugador de Poker a los grupos de interés
