### ISSUE TITLE
Preguntas sobre el diccionario de datos

### ISSUE THREAD

**Issue by aroaaredondo** [UNIZAR-30226-2024-08/documentacion#7]
En un usuario Registrado es necesario que nos guardemos el nombre completo?

Habría que guardar el historial de partidas en el usuario registrado?

La descripción de partida no sería la de sala? (hay confusion con eso)

**Comment by titoMar008** [comment]
### En un usuario Registrado es necesario que nos guardemos el nombre completo?
> Yo creo que no es necesario guardar el nombre real de un usuario, ya que con el nombre de usuario y el correo es más que suficiente.

### Habría que guardar el historial de partidas en el usuario registrado?
> Así es, un usuario registrado tendrá enlazada su historial de partidas.

### La descripción de partida no sería la de sala? (hay confusión con eso)
> Se ha propuesto una descripción de partida y sala para ver si ahora estos conceptos son menos confusos
