### ISSUE TITLE
Error en RF 

### ISSUE THREAD

**Issue by aroaaredondo** [UNIZAR-30226-2024-08/documentacion#8]
**Descripción del error**
En la parte De Usuarios Autenticados:
> RFUA-4 b. nombra al observador

En la parte de Jugadores: 
> No existe un requisito para BlackJack que diferencie entre sala pública o privada.

En la parte de jugadores de Blackjack:
> RFJB-1: cuando abandonamos, abandonamos todo no? y se pausa la sala no la partida.

En la parte de jugadores de Poker:
>  RFJP-2 : es un requisito del blackJack aqui no deberia de estar

**Resultado Esperado**
En la parte De Usuarios Autenticados:
> Quitar la parte de observador

En la parte de Jugadores: 
> Añadir un requisito para cada sala

En la parte de los observadores: eliminarlo todo.

En la parte de jugadores de Blackjack:
> RFJB-1: abandonar sala creada y pausar sala.

En la parte de jugadores de Poker:
> Quitar los requisitos que no tengan que ver con el poker

**Contexto Adicional**
REVISAR LOS MISMOS ERRORES EN LA FORMALIZACIÓN DE REQUISITOS.

**Comment by titoMar008** [comment]
### En la parte De Usuarios Autenticados:
> Parte del observador borrada.

### En la parte de Jugadores:
> Ya se han añadido los requisitos para la sala pública y la sala privada en el blackjack.

### En la parte de jugadores de Blackjack:
> Se ha cambiado a que se abandone y se pause la sala y no la partida.

### En la parte de jugadores de Poker:
> Se han eliminado los requisitos del blackjack en el poker.

### REVISAR LOS MISMOS ERRORES EN LA FORMALIZACIÓN DE REQUISITOS.
> Revisados 👍
