### ISSUE TITLE
Proceso de negocio 1.3

### ISSUE THREAD

**Issue by titoMar008** [UNIZAR-30226-2024-08/documentacion#9]
Añado una posibilidad de modelo de negocio, elegid una y borrar la otra.

**Comment by titoMar008** [comment]
cc/ @aroaaredondo @carlotamgm

**Comment by carlotamgm** [comment]
Se ha elegido uno de los dos procesos de negocio propuestos, y se ha modificado levemente:

El sistema ofrece al usuario los siguientes servicios: la posibilidad de empezar una nueva partida de BlackJack o de Póker y la posibilidad de unirse a una partida ya existente. También permite al usuario registrado personalizar el inventario: sus cartas, monedas y su avatar.
El usuario debe registrarse previamente para poder jugar en las partidas y realizar apuestas.
